name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Get tag
      uses: olegtarasov/get-tag@v2.1
      id: tagName

    - name: Build and push tagged docker image on master
      uses: docker/build-push-action@v2.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: maruina/docker-grpc-health-probe
        tags: ${{ steps.tagName.outputs.tag }}