name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Get tag
      uses: olegtarasov/get-tag@v2.1
      id: tagName

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push tagged docker image on master
      uses: docker/build-push-action@v2.3.0
      with:
        tags: maruina/docker-grpc-health-probe:${{ steps.tagName.outputs.tag }}